FROM node:22-bookworm

ARG ARG_PORT=8282


RUN apt update && apt upgrade -y && \
apt clean && \
rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN npm install -g npm@10.8.2 && \
npm install -g pnpm && \
pnpm --version

USER node

RUN export SHELL="bash" && pnpm setup

ENV PNPM_HOME="/home/node/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"

RUN SHELL="bash" && \
pnpm config set store-dir "${PNPM_HOME}/store" && \
pnpm install -g typescript && \
pnpm --version && tsc --version

WORKDIR /workspace/backend

EXPOSE ${ARG_PORT}

CMD ["/bin/sh", "-c", "pnpm i && pnpm start"]
