name: ${APP}-env

services:
  backend_dev_server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile-dev-server
      args:
        - ARG_PORT=${PORT}
    image: ${APP}-dev-server-img
    container_name: ${APP}-dev-server-container
    volumes:
      - ../../backend:/workspace/backend
    ports:
      - '${PORT}:${PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "pgrep next-server && echo 'Dev server is running...' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile-web
    image: ${APP}-webapp-img
    container_name: ${APP}-web-container
    user: node
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    environment:
      - BACKEND_API_URL=http://backend_dev_server:${PORT}
    volumes:
      - ../../frontend:/workspace/frontend:cached
      - ${HOME}/.local/share/pnpm:/home/node/.local/share/pnpm:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      backend_dev_server:
        condition: service_healthy
