FROM alpine:latest

ARG ARG_PB_VERSION=0.22.16
ARG ARG_PB_PORT=8080

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${ARG_PB_VERSION}/pocketbase_${ARG_PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
# COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# COPY ./pb_hooks /pb/pb_hooks

EXPOSE ${ARG_PB_PORT}

# start PocketBase
ENV PB_PORT=${ARG_PB_PORT}
CMD /pb/pocketbase serve --http=0.0.0.0:${PB_PORT}
